Vagrant.configure("2") do |config|

  # Servidor Web
  config.vm.define :web do |web| # Cambiado a "web"
    web.vm.box = "debian/bookworm64" # Imagen de Debian 12 (bookworm)
    web.vm.hostname = "web-andy" # Nombre del host simplificado
    web.vm.synced_folder ".", "/vagrant", disabled: true
    
    # Red pública (con salida a Internet)
    web.vm.network :public_network,
      :dev => "br0", # Interfaz de puente
      :mode => "bridge",
      :type => "bridge" 

    # Red privada (muy aislada)
    web.vm.network :private_network,
      :libvirt__network_name => "red_intra", # Nombre de la red privada
      :libvirt__dhcp_enabled => false, # DHCP deshabilitado
      :ip => "10.0.0.2", # IP del servidor web
      :libvirt__forward_mode => "veryisolated" 
  end

  # Servidor de Base de Datos
  config.vm.define :bd do |db| # Cambiado a "bd"
    db.vm.box = "debian/bookworm64" # Imagen de Debian 12 (bookworm)
    db.vm.hostname = "bd-andy" # Nombre del host simplificado
    db.vm.synced_folder ".", "/vagrant", disabled: true

    # Red pública (con salida a Internet)
    db.vm.network :public_network,
      :dev => "br0", # Interfaz de puente
      :mode => "bridge",
      :type => "bridge" 

    # Red privada (muy aislada)
    db.vm.network :private_network,
      :libvirt__network_name => "red_intra", # Nombre de la red privada
      :libvirt__dhcp_enabled => false, # DHCP deshabilitado
      :ip => "10.0.0.3", # IP del servidor de base de datos
      :libvirt__forward_mode => "veryisolated" 
  end
end
